logging:
  level:
    root: info
    pl.toponavigator: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
spring:
  application:
    name: TopoNavigatorAPI
  banner:
    location: classpath:/banner/doom-banner-TopoNavigator.txt
  datasource:
    url: 'jdbc:postgresql://localhost:5432/TopoNavigator_DB'
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
#  autoconfigure:
#    exclude:
#      org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
mybatis:
  mapperLocations: classpath:/mybatis/mappers/*.xml
