package pl.toponavigator.utils;

public enum ErrorTypeEnum {
  UNDEFINED_ERROR,
  USER_NOT_FOUND,
  AUTH_ERROR,
  ACCESS_TOKEN_EXPIRED,
  REFRESH_TOKEN_EXPIRED,
  REFRESH_TOKEN_ERROR,
  ACCESS_TOKEN_ERROR,
  BAD_CREDENTIALS,
  SIGNATURE_ERROR,
  MALFORMED_JWT_TOKEN,
  RESOURCE_ALREADY_EXIST,
  RESOURCE_INSERT_ERROR,
  DELETE_ERROR_RESOURCE_DOESNT_EXIT
}
