package pl.toponavigator.utils;

public enum ErrorTypeEnum {
    UNDEFINED_ERROR,
    USER_NOT_FOUND,
    AUTH_ERROR,
    ACCESS_TOKEN_EXPIRED,
    REFRESH_TOKEN_EXPIRED,
    REFRESH_TOKEN_ERROR,
    ACCESS_TOKEN_ERROR,
    BAD_CREDENTIALS,
    SIGNATURE_ERROR,
    MALFORMED_JWT_TOKEN
}
